# Generated by Django 5.2.8 on 2025-11-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='lname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
