# Generated by Django 5.2.8 on 2025-11-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_project', '0002_author_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
