# Generated by Django 5.2.8 on 2025-11-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_project', '0003_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
