# Generated by Django 5.2.8 on 2025-11-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_project', '0005_remove_post_author_remove_post_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcategory',
            name='id',
        ),
        migrations.AddField(
            model_name='bookcategory',
            name='pk',
            field=models.CompositePrimaryKey('book_id', 'category_id', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
