# Generated by Django 5.2.8 on 2025-11-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_project', '0006_remove_bookcategory_id_bookcategory_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='pk',
            field=models.CompositePrimaryKey('book', 'category', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
