# Generated by Django 5.2.8 on 2025-11-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_project', '0007_alter_bookcategory_pk'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookcategory',
            unique_together={('book', 'category')},
        ),
    ]
